// <auto-generated/>

namespace TweeterTotters
{
    using System;
    using System.Windows;
    
    /// <summary>
    /// Necessary for the WPF application to run.
    /// </summary>
    public partial class App : Application
    {
    }
}
